# Generated by Django 4.1 on 2023-03-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='img_url',
            field=models.CharField(max_length=500),
        ),
    ]
